In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
data = pd.read_csv("smartcart_customers.csv")

In [3]:
data.sample(5)

,ID,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,MntWines,...,MntFishProducts,MntSweetProducts,MntGoldProds,NumDealsPurchases,NumWebPurchases,NumCatalogPurchases,NumStorePurchases,NumWebVisitsMonth,Complain,Response
1236,4174,1956,Master,Together,55249.0,0,1,17-04-2014,81,97,...,2,0,11,1,2,1,4,3,0,0
357,6184,1969,PhD,Married,68462.0,0,0,12-12-2012,6,561,...,84,128,48,1,3,3,8,1,0,0
1213,697,1969,Graduation,Together,74918.0,0,0,12-03-2013,78,972,...,25,19,59,1,5,9,6,3,0,0
2125,2088,1972,Graduation,Together,84906.0,0,0,04-10-2013,98,997,...,99,30,76,1,5,6,12,2,0,0
1546,6365,1987,2n Cycle,Married,30390.0,0,0,02-09-2013,5,10,...,25,1,20,1,2,0,3,6,0,0

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2240 entries, 0 to 2239
Data columns (total 22 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ID                   2240 non-null   int64
 1   Year_Birth           2240 non-null   int64
 2   Education            2240 non-null   object
 3   Marital_Status       2240 non-null   object
 4   Income               2216 non-null   float64
 5   Kidhome              2240 non-null   int64
 6   Teenhome             2240 non-null   int64
 7   Dt_Customer          2240 non-null   object
 8   Recency              2240 non-null   int64
 9   MntWines             2240 non-null   int64
 10  MntFruits            2240 non-null   int64
 11  MntMeatProducts      2240 non-null   int64
 12  MntFishProducts      2240 non-null   int64
 13  MntSweetProducts     2240 non-null   int64
 14  MntGoldProds         2240 non-null   int64
 15  NumDealsPurchases    2240 non-null   int64
 16  NumWebPurchases      2240 non-null   int64
 17  NumCatalogPurchases  2240 non-null   int64
 18  NumStorePurchases    2240 non-null   int64
 19  NumWebVisitsMonth    2240 non-null   int64
 20  Complain             2240 non-null   int64
 21  Response             2240 non-null   int64
dtypes: float64(1), int64(18), object(3)
memory usage: 385.1+ KB

In [5]:
data["Year_Birth"].dtype

dtype('int64')

In [6]:
data.isnull().sum()

ID                      0
Year_Birth              0
Education               0
Marital_Status          0
Income                 24
Kidhome                 0
Teenhome                0
Dt_Customer             0
Recency                 0
MntWines                0
MntFruits               0
MntMeatProducts         0
MntFishProducts         0
MntSweetProducts        0
MntGoldProds            0
NumDealsPurchases       0
NumWebPurchases         0
NumCatalogPurchases     0
NumStorePurchases       0
NumWebVisitsMonth       0
Complain                0
Response                0
dtype: int64

# Data Preprocessing

## 1. Handle Missing Values

In [7]:
data["Income"] = data["Income"].fillna(data["Income"].median())

In [8]:
data.isnull().sum()

ID                     0
Year_Birth             0
Education              0
Marital_Status         0
Income                 0
Kidhome                0
Teenhome               0
Dt_Customer            0
Recency                0
MntWines               0
MntFruits              0
MntMeatProducts        0
MntFishProducts        0
MntSweetProducts       0
MntGoldProds           0
NumDealsPurchases      0
NumWebPurchases        0
NumCatalogPurchases    0
NumStorePurchases      0
NumWebVisitsMonth      0
Complain               0
Response               0
dtype: int64

## Feature Engineering

In [9]:
# Birth-Date -> Age
data["Age"] = 2026-data["Year_Birth"]

In [10]:
data.sample()

,ID,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,MntWines,...,MntSweetProducts,MntGoldProds,NumDealsPurchases,NumWebPurchases,NumCatalogPurchases,NumStorePurchases,NumWebVisitsMonth,Complain,Response,Age
508,3386,1992,Graduation,Married,34935.0,0,0,21-06-2013,71,34,...,10,20,1,2,1,4,7,0,0,34

In [11]:
# Customer-Joining-Date -> Customer Tenure Days

data["Dt_Customer"] = pd.to_datetime(data["Dt_Customer"],dayfirst=True)

reference_date = data["Dt_Customer"].max()

data["Customer_Tenure_Days"] = (reference_date - data["Dt_Customer"]).dt.days

In [12]:
# Total Spending :

data["Total_Spending"] = (data["MntWines"] + data["MntFruits"] + data["MntMeatProducts"] 
                        + data["MntFishProducts"] + data["MntSweetProducts"]+ data["MntGoldProds"])

In [13]:
# Total Children :

data["Total_Children"] = (data["Kidhome"] + data["Teenhome"])

In [14]:
# Education :

data["Education"].value_counts()

data["Education"] = data["Education"].replace({
    "Graduation" : "Graduate",
    "PhD" : "Postgraduate","Master" : "Postgraduate",
    "2n Cycle" : "Undergraduate","Basic" : "Undergraduate"
})

In [15]:
# Marital-Status :

data["Marital_Status"].value_counts()

data["Living_With"] = data["Marital_Status"].replace({
    "Married" : "Partner","Together" : "Partner",
    "Divorced" : "Single","Widow" : "Single","Alone" : "Single","Absurd" : "Single","YOLO" : "Single"
})